### ISSUE TITLE
Is adding spaces after ( and before ) is acceptable by community?

### ISSUE THREAD

**Issue by PSVortex** [PoshCode/PowerShellPracticeAndStyle#109]
Hi,

I want to know if adding spaces after **(** and before **)** is acceptable by community:

```
function Get-CredentialEx {
param( $Message, $UserName )
    if ( $PSVersionTable.PSVersion.Major -ge 3 ) {
        Get-Credential -Message $Message -UserName $UserName
    } else { Get-Credential }
}
```

`If ( !( $x -eq "a" )) { $true }`

I find such code more easy to read.

**Comment by darkoperator** [comment]
For me it is

**Comment by pauby** [comment]
I do this myself a lot particularly around longer / more complex code. It helps to make it clearer to read which is one of the most important things (for me 😀 ) in writing code.

**Comment by Jaykul** [comment]
I'm ok with it too, although I'm not sure I'd want to require it...

I suspect the common aversion to this in style guides has much to do with arbitrary line-length rules 😉

**Comment by timkingwriter** [comment]
Perfectly fine with me! 

Anything that increases maintainer comprehension is great in my book.

**Comment by Bill-Stewart** [comment]
I'm not sure I understand. Multiple expressions would be written as follows:

    if ( (-not ($a -eq "a")) -or ($b -eq "b") ) { ...

In other words: The `if` statement's outer `(` has a trailing space, and the `if` statement's outer `)` has a leading space. Expressions _within_ the outer `(` and `)` don't have extra spaces.

This adds readability, IMO, since the outer `(` and `)` stand out as syntactically part of the `if`.

**Comment by PSVortex** [comment]
@Bill-Stewart Such way is even better, but reality show us that people will not add extra space between '))' ever. So it will always be like:

`if ((-not ($a -eq "a")) -or ($b -eq "b")) { ...

**Comment by Bill-Stewart** [comment]
I recommend reformatting as what I wrote earlier:

    if ( (-not ($a -eq "a")) -or ($b -eq "b") ) { ...

That is, a space after outer `(` and a space before outer `)` to indicate that they are part of the `if`. I also use the same convention, to maintain consistency, with other language statements that require `( )`; e.g.:

    for ( $a = 0; $a -lt $collection.Count; $a++ ) { ...
    foreach ( $item in $collection ) { ...
    while ( $condition ) { ...
    do { ... } while ( $condition )
    do { ...} until ( $condition )

**Comment by jdgregson** [comment]
I vote no. Not at all okay in any language.
