### ISSUE TITLE
Auto format

### ISSUE THREAD

**Issue by midacts** [PoshCode/PowerShellPracticeAndStyle#110]
Does something like `gofmt` for golang or `terraform format` for Terraform exist for PowerShell?
It would be awesome for VS code or PSScriptAnalyzer to auto enforce the standards and even to be able to auto format documents.

It can take a loooot of time to refactor/format code.

**Comment by Midacts** [comment]
Agreed. So far that is the only option I've seen.
Other than that, I thought of making PSScriptAnalyzer rules.
Something native to VS Code might be better.

But as you alluded to, it is limited. We wouldn't be able to enforce all the settings outlines in the repo.

**Comment by pauby** [comment]
I believe the current thoughts is that PSScriptAnalyzer within VS Code flags the rule violations up but it's up to you to resolve them. Which I think is a nice compromise between enforcing it (which it could get wrong) and doing nothing.

**Comment by bergmeister** [comment]
Can you  be more specific about what you describe as limited? Is it that you would like to customize/tweak one of the 3 built om style rules or are the style rule definitions in PSSA about braces, whitespace, etc. not sufficient?
VSCode has 3 styles that map to certain PSSA style rule configurations but using a setting file you can even get warnings when your style is not matching. Ctrl+K+F on a selection auto formats the code.

**Comment by Midacts** [comment]
Maybe I am not aware of all the settings you are pointing out?

user settings -> powershell.codeformatting.*

I still don't think it is enforcing all the rules outlined in this repo.
making sure things like function, if, foreach, etc are all lowercase, that the function names are pascal case, auto formatting comment based help, parameters, etc.

Basically like terraform format, gofmt, etc works.

**Comment by bergmeister** [comment]
@Midacts There is an open issue (that is up for grabs) in PSSA to do the formatting with the correct casing: https://github.com/PowerShell/PSScriptAnalyzer/issues/767
Sorry, I haven't used terraform format, gofmt before but will look it up

**Comment by Jaykul** [comment]
I think this can be closed now that `Invoke-Formatter` ships in PSScriptAnalyzer?
