### ISSUE TITLE
param() or param ()

### ISSUE THREAD

**Issue by jdgregson** [PoshCode/PowerShellPracticeAndStyle#128]
I came here to learn a style that I could apply to my code to achieve consistency. After going over the first page, [Code Layout & Formatting](https://github.com/PoshCode/PowerShellPracticeAndStyle/blob/master/Style-Guide/Code-Layout-and-Formatting.md), I noticed that every example wrote `param` as `param()` (note the lack of a space). I adapted my scripts accordingly. Then I read the second page, [Function Structure](https://github.com/PoshCode/PowerShellPracticeAndStyle/blob/master/Style-Guide/Function-Structure.md), and immediately noticed that every single example on that page used `param` like `param ()` (note the space).

So, in the name of consistency, which is correct?

**Comment by ryanspletzer** [comment]
IMHO `param ()`

**Comment by pauby** [comment]
Both. Personal taste. I use `param()`.

**Comment by jdgregson** [comment]
@pauby Well half of the reason style guides exist is to eliminate personal taste and enforce a standard. But as this small detail doesn't seem to have been addressed, I will personally choose to use `param ()` since the following blocks, like `process {`, have a space before the bracket. Other keywords, like `if ()` and `foreach ()` usually have a space before the parentheses as well.

**Comment by pauby** [comment]
@jdgregson Style guides are not there to _eliminate_ personal taste or enforce a standard. And unless I'm mistaken (and somebody correct me if I'm wrong) that's not why this style guide exists either.

Style guides exist to suggest a style that can be used and explain why that style is chosen over the others. There is no elimination or enforcement. You can still choose to do what you want to do.

The important thing in whatever style you choose (whether it's this, bracket pairs or something else) is consistency. Be consistent.

**Comment by jdgregson** [comment]
@pauby Fair point. The style guide itself doesn't enforce anything, but individual shops can choose to strictly abide by a style guide, and "enforce" it themselves. That is what I have chosen to do with PoshCode's style guide for my own projects. And as for "Be consistent.", I couldn't agree more. That's what this issue was about to begin with. This project should consistently use either `param()` or `param ()`, not both. 

As for which one to use, `param ()` is used 15 times in this project, while `param()` is only used 7 (including todos), so it appears that `param ()` at least **should be** preferred. I'll submit a PR later changing `param()` to `param ()` where appropriate.

**Comment by Schwitzd** [comment]
In the page [About Functions Advanced Parameters](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters?view=powershell-6) is always used `Param()`

**Comment by jdgregson** [comment]
@Schwitzd Huh, you're right. They do the same [here](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced?view=powershell-6):

```
function Send-Greeting
{
    [CmdletBinding()]
    Param(
        [Parameter(Mandatory=$true)]
        [string] $Name
    )

    Process
    {
        Write-Host ("Hello " + $Name + "!")
    }
}
```

I guess that would be the more correct way after all, since they wrote the language. However, I will not be adopting that horrid brace style -- I'll be sticking with PoshCode's OTBS recommendation for that detail.

**Comment by Schwitzd** [comment]
@jdgregson 
They use also capital P.
Where is the PoshCode's recommendation?

**Comment by rkeithhill** [comment]
Seems like language keywords should be lower-case like `function` in that example.

**Comment by Jaykul** [comment]
Yeah, `param()` is the only place where I frequently leave the space out, but I prefer the space for consistency. I've merged the PR so we're now internally consistent 😁
