### ISSUE TITLE
Formatting not symmetrical within parenthesis

### ISSUE THREAD

**Issue by JVimes** [PoshCode/PowerShellPracticeAndStyle#136]
Here's before code formatting:  
```powershell
function Invoke-Build([ValidateScript({ /*...*/ })] $param1)
{
}
```
And after:  
```powershell
#                                     ⮦Space     ⮦No space
function Invoke-Build([ValidateScript( { /*...*/ })] $param1)
{
}
```

The spacing within the ValidateScript's parenthesis is not symmetrical, and I'd expect it to be.

**Comment by Jaykul** [comment]
I agree with you, so I'm pretty sure you meant to post this as a bug against the [PowerShell/PSScriptAnalyzer](/PowerShell/PSScriptAnalyzer) project -- or maybe as a comment on PowerShell/PSScriptAnalyzer/issues/1168

**Comment by JVimes** [comment]
Oops, right, wrong repo. I think I meant to do [PowerShell/vscode-powershell](https://github.com/PowerShell/vscode-powershell), but it does appear the formatter is part of the script analyzer, so I'd have been wrong anyway ;)
