### ISSUE TITLE
Do you (all) still care about non-style Best Practices?

### ISSUE THREAD

**Issue by Jaykul** [PoshCode/PowerShellPracticeAndStyle#14]
I've been finding it hard to draw the line on style and "best practices," because obviously good style is a best practice :grinning: 

I'm thinking about using this as a jumping off point to finally write what was originally going to be a series of blog posts that were going to look roughly like this: 
https://github.com/PoshCode/PSStyleGuide/blob/master/ExampleExample.md

The idea was to take a single "Best Practice" and write a series of "DO" or "DO NOT" posts for it, using the pattern:

# Best Practice: <whatever>
#### Notes:

And then index them all and cross-tabulate and some junk, maybe make an ebook out of it. But then came the _PowerShell Best Practices_ book from Ed Wilson (which is, frankly, the worst named PowerShell book I know of), and the "Community Practices_ ebook from PowerShell.org, and I've still never gotten around to writing them.

So anyway, the question is: is anyone interested in fleshing out the Best Practices stuff that's already in the document here, or the thoughts that are in [TODO.md](https://github.com/PoshCode/PSStyleGuide/blob/master/TODO.md) ... or should we trim some of that stuff out and keep this firmly a style guide (ala PEP8)

**Comment by mattmcnabb** [comment]
I'd be interested! I definitely think there should be a clear separation between a style guide and a best practice guide. Best practices can encompass so many things - best practices for security/credentials, best practices for using .NET classes, etc.

A style guide should be all about creating a relatively consistent community coding style for maximum readability and shareability. This is essential for continued collaboration on open projects and should be relatively static.
