### ISSUE TITLE
Indentation advice is bad/wrong

### ISSUE THREAD

**Issue by aaroneg** [PoshCode/PowerShellPracticeAndStyle#141]
`Usually you will press the [Tab] key to indent, but most editors can be configured to insert spaces instead of actual tab characters. For most programming languages and editors (including PowerShell ISE) the default is four spaces, and that's what we recommend. Different teams and projects may have different standards, and when contributing to a project, you should abide by the predominant style, of course.`

Tabs are the best way to indent. The same editors that can be configured to insert spaces can be configured to show tab characters at whatever width the user prefers. One tab per indent level.

**Comment by pauby** [comment]
> Tabs are the best way to indent.

I think you missed off `in my opinion` at the end of that statement, and off of the end of your Title. Others would disagree with you.

Microsoft recommends 4 spaces for .NET languages. ([C# is here](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions#layout-conventions) but I understand they do this for all of them). C# and PowerShell being so closely tied it's considered best practice to follow those conventions.

**Comment by aaroneg** [comment]
It's your repo - you are under no obligation to accept that it's an issue.

**Comment by kilasuit** [comment]
I agree with @pauby 

Tabs vs spaces is a debate in itself and generally speaking in most cases a totally pointless one to have.

**Comment by pauby** [comment]
Whether you have tabs or spaces, just be consistent. Neither is right. Neither is wrong. There is only _suggested_ best practice and reasons why it's best practice.

What you use in your code is up to you.

**Comment by Objections** [comment]
If all programmers where robots in adhering to best practice then "tabs for intention. Spaces for alignment" is the superior approach. 
You will however always get someone using tabs when intenting braking alignment if you change tab size.. 
"Spaces only" is therfore superior in practice if you have more than one maintainer.
Can we close this?

**Comment by Bill-Stewart** [comment]
I disagree that "4 spaces is best practice" (if you rephrase as "a very common practice" then I agree). I use 2 spaces as it's far more readable to me (2 spaces are my "best practice"). 3 spaces is OK too, but 4 seems excessive IMO. But I agree that this topic has already been beat to death (LOL).

**Comment by copdips** [comment]
This topic is about space vs tab, not how many spaces.
A common sense is to **display** spaces instead of tabs, of course you can configure your editor to replace tab by space when you **write** code.

I fully agree with the original practices, nothing need to be changed.

**Comment by Bill-Stewart** [comment]
> This topic is about space vs tab, not how many spaces.
Correct. I was disagreeing with the statement "4 spaces is best practice" and was pointing out that's a matter of opinion.
