### ISSUE TITLE
Is it better to use $PSItem vs $error[0] or $_

### ISSUE THREAD

**Issue by ebmarquez** [PoshCode/PowerShellPracticeAndStyle#143]
Which method is recommended, PSItem seems to be better than using $_ IMO.   What's the general recommendation?

**Comment by Bill-Stewart** [comment]
IMO `PSItem` isn't preferred. I never use it as `$_` is documented and easily understood. (It seems to me that `$_` is used _far_ more often, and introducing `PSItem` could even be confusing.)

**Comment by ebmarquez** [comment]
I've been using $PSItem.Exception.Message. thanks for the input.
