### ISSUE TITLE
Correct formatting

### ISSUE THREAD

**Issue by serjou1** [PoshCode/PowerShellPracticeAndStyle#145]
Let's assume, we have following code:

```
$numberOfBooks = (Get-ChildItem $myBooksDir -Recurse -File -Include '*.txt', '*.pdf', '*.doc*' | Measure-Object).Count
if ($numberOfBooks -gt 1000) {
    Write-Host "There are $numberOfBooks books in the folder. Are you sure you can read that much?"
}
```

First line of this code has length 118, so we should make it shorter. The first thing that comes to mind is to move `Measure-Object).Count` on the next line. But what is the right approach in this case?

Have 4 spaces from beginning of line:
```
$numberOfBooks = (Get-ChildItem $myBooksDir -Recurse -File -Include '*.txt', '*.pdf', '*.doc*' |
    Measure-Object).Count
if ($numberOfBooks -gt 1000) {
    Write-Host "There are $numberOfBooks books in the folder. Are you sure you can read that much?"
}
```

Have 4 spaces from `(`:
```
$numberOfBooks = (Get-ChildItem $myBooksDir -Recurse -File -Include '*.txt', '*.pdf', '*.doc*' |
                     Measure-Object).Count
if ($numberOfBooks -gt 1000) {
    Write-Host "There are $numberOfBooks books in the folder. Are you sure you can read that much?"
}
```

Or have 4 spaces from `G`:
```
$numberOfBooks = (Get-ChildItem $myBooksDir -Recurse -File -Include '*.txt', '*.pdf', '*.doc*' |
                      Measure-Object).Count
if ($numberOfBooks -gt 1000) {
    Write-Host "There are $numberOfBooks books in the folder. Are you sure you can read that much?"
}
```

**Comment by ChrisLGardner** [comment]
Remove the Measure-Object entirely since it's not adding anything that isn't already provided by PS.

You could conceivably also drop the parents and name the variable books, then in the if do $books.count, because presumably you actually care what the books are later in your script so should only look them up once and reuse that variable and it's contents later.

**Comment by serjou1** [comment]
That script is just for example. I just wonder to know the best approach in such cases

**Comment by ChrisLGardner** [comment]
Whatever looks right to you is probably the best answer, it's probably a heavily opinionated area like a few others around style. Personally I prefer the second so it's more clear it's part of that single command.

**Comment by ryan-jan** [comment]
Taking into account that the code is obviously for demo purposes only. I would suggest splatting the parameters for `Get-ChildItem` for example

```powershell
$Params = @{
    Path = $MyBooksDir
    Recurse = $true
    File = $true
    Include = '*.txt', '*.pdf', '*.doc*'
}
$NumberOfBooks = (Get-ChildItem @Params | Measure-Object).Count
if ($NumberOfBooks -gt 1000) {
    Write-Host "There are $NumberOfBooks books in the folder. Are you sure you can read that much?"
}
```

Also I would use PascalCase for variable names to align with the PowerShellPracticeAndStyle Capitalization guidelines but this is obviously personal preference.

**Comment by Jaykul** [comment]
For what it's worth (and to demonstrate that this is very much a matter of taste), I would probably just leave it that long. I've got 24" monitors, and my "you should wrap soon" line is set at 120, but ....

But if I did want to shorten that, I would go ahead and wrap on the parenthesis to give myself more space, and then maybe write it like this:

```PowerShell
$numberOfBooks = (
    Get-ChildItem $myBooksDir -Recurse -File -Include '*.txt', '*.pdf', '*.doc*' |
        Measure-Object
).Count

if ($numberOfBooks -gt 1000) {
    Write-Host "There are $numberOfBooks books in the folder. Are you sure you can read that much?"
}
```
