### ISSUE TITLE
Inconsistencies or not mentioned special cases

### ISSUE THREAD

**Issue by nightroman** [PoshCode/PowerShellPracticeAndStyle#16]
> You should us a single space around parameter names and operators, including
> comparison operators and math and assignment operators, even when the spaces
> are not necessary for PowerShell to correctly parse the code.

Used examples, for instance this

``` powershell
parameter(Mandatory=$true)
```

does not have spaces around "=". Personally, I also follow the rule "spaces
around operators" except: a) attribute values; b) parameter default values.
Perhaps the guidelines should mention these cases.

> Nested expressions $( ... ) and script blocks { ... } should have a single
> space inside them to make code stand out and be more readable.

This used example

``` powershell
[ValidateScript({$_ -ge (get-date)})]
```

does not use spaces inside the script block. Perhaps it is a special case when
this is appropriate. Then this should be mentioned.

**Comment by darkoperator** [comment]
Yep need to get that fixed. Thanks for pointing it out

**Comment by Jaykul** [comment]
I'll admit I tend to leave out the spaces in attributes, but I'm also happy to just say I should have had spaces to follow the guidelines ;-)
