### ISSUE TITLE
Best Practices and Style Guide: One Project or Two

### ISSUE THREAD

**Issue by Jaykul** [PoshCode/PowerShellPracticeAndStyle#21]
We are taking over the Best Practices book, in addition to this style guide, so the question is: shall I 

1. Make folders in this project for the Style Guide and Best Practices?
2. Move all the Best Practices stuff to a new project?

**Comment by Jaykul** [comment]
My personal vote goes for a single project, because I think they're so closely related we'll be hard-put to keep all the issues and conversations in the right project otherwise.

**Comment by bryanwinstead** [comment]
I agree with. Single project makes more sense.

**Comment by PowerSchill** [comment]
I agree. They are sometimes the same.

**Comment by Jaykul** [comment]
One it is.
