### ISSUE TITLE
Avoid backtick splatting example could be improved

### ISSUE THREAD

**Issue by rkeithhill** [PoshCode/PowerShellPracticeAndStyle#29]
The text lists this example:
```powershell
$params = @{Class=Win32\_LogicalDisk;
      Filter='DriveType=3';
      ComputerName=SERVER2}
```
Note that the semicolons are unnecessary and it is missing quotes.  This works:
```powershell
$params = @{ Class = 'Win32\_LogicalDisk'
             Filter = 'DriveType=3'
             ComputerName = 'SERVER2'}
```

**Comment by Jaykul** [comment]
That's much better.

I think we should name the variable based on the command you're going to call (either `GetWmiObject` or `GetWmiObjectParam`) and I usually prefer that if you're going to line-wrap, you wrap right away:

```
$GetWmiObject = @{
    Class = 'Win32\_LogicalDisk'
    Filter = 'DriveType=3'
    ComputerName = 'SERVER2'
}
Get-WmiObject @GetWmiObject

**Comment by rkeithhill** [comment]
Yeah, ditto on the wrap right away comment. That's usually how I initialize hashtables.  

Also, is there a whitespace rule that says put whitespace between `$var=value` e.g. `$var = value`.  That's a readability issue IMO.

**Comment by Jaykul** [comment]
Yeah [spaces around parameters and operators](https://github.com/PoshCode/PowerShellPracticeAndStyle/blob/master/Style%20Guide/English.md#spaces-around-parameters-and-operators).

**Comment by darkoperator** [comment]
Yep agrede, the original guide i created it over a year ago so it would fit my style for when people committed to my modules. I work a lot of stuff on a SSH terminal to Linux box that then pushes code to a ruby framework for stuff and wanted similarities there. The rule I believe is a nice to have but optional there for white spaces.

**Comment by Jaykul** [comment]
I fixed that example.
