### ISSUE TITLE
PIPE-01 - Can I delete this?

### ISSUE THREAD

**Issue by Jaykul** [PoshCode/PowerShellPracticeAndStyle#31]
I'm 100% sure that the _terrible_ example in [the great debate about pipelines](http://powershell.org/wp/2013/07/16/powershell-great-debate-piping-in-a-script/) is the only reason we got the [pipe-01](https://github.com/PoshCode/PowerShellPracticeAndStyle/blob/master/Best%20Practices/pipe-01-avoid-using-pipelines-in-scripts.md) rule, and I'm 100% dead-set against it.

I would like to just delete the chapter, and will do so if no one has any objections?

**Comment by darkoperator** [comment]
None from me

**Comment by KirkMunro** [comment]
No objection here.

--
*Kirk Munro *
Poshoholic, Microsoft MVP
Blog <http://poshoholic.com/> | Twitter <http://twitter.com/poshoholic> |
LinkedIn <http://ca.linkedin.com/in/kirkmunro> | GitHub
<http://github.com/KirkMunro> | Facebook
<http://www.facebook.com/#%21/kirk.munro>

Need a PowerShell SME for a project at work? Contact me
<http://poshoholic.com/contact-me/>!

**Comment by mwjcomputing** [comment]
No objection

On May 30, 2015, at 3:20 AM, Joel Bennett <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm 100% sure that the terrible example in the great debate about pipelines<http://powershell.org/wp/2013/07/16/powershell-great-debate-piping-in-a-script/> is the only reason we got the pipe-01<https://github.com/PoshCode/PowerShellPracticeAndStyle/blob/master/Best%20Practices/pipe-01-avoid-using-pipelines-in-scripts.md> rule, and I'm 100% dead-set against it.

I would like to just delete the chapter, and will do so if no one has any objections?

-

**Comment by rodmhgl** [comment]
None here.
