### ISSUE TITLE
Formatting these documents

### ISSUE THREAD

**Issue by Jaykul** [PoshCode/PowerShellPracticeAndStyle#34]
I wrote the Contributing guidelines before we pulled in the Best Practices book, and I've been reviewing that book and feel like it's broken up way too much (especially considering many of the documents are nothing but a headline, less than a whole paragraph).

https://github.com/PoshCode/PowerShellPracticeAndStyle/blob/master/CONTRIBUTING.md

I'm thinking perhaps the best solution for the sake of consistency and readability is to _break up the Style Guide_ by it's top-level categories, and _unify the Best Practices_ on it's top-level categories, one file each:

* Style Guide
  * Code Layout
  * Commenting
  * Naming Conventions
  * Function Structure
  * Security
  * Metadata (Supported Versions)
* Best Practices
  * Readability
  * Documentation (Commenting)
  * Metadata (Supported Versions)
  * Error Handling
  * Output
  * Performance
  * Function Structure (aka "TOOL" - writing good, reusable functions)
  * Interop (aka "PURE" -- PowerShell vs. .Net vs. Native)
  * Waste

### Any problems with that?

There's obviously some overlap right now, here's my thoughts on removing it:

* The _Best Practices_ Readability and Documentation sections should probably both be in the _Style Guide_ instead.
* The _Style Guide_ section on PowerShell Supported Version and Security should probably both be in _Best Practices_ instead.
* The _Best Practices_ "TOOL"s section should lean heavily on the _Style Guide_ for details, but deserves to stay in _Best Practices_.

**Comment by Jaykul** [comment]
OK, after puzzling over it, here's my new proposed documents:

* Style Guide
  * Code Layout and Formatting
  * Function Structure
  * Documentation and Commenting
  * Readability
  * Naming Conventions
* Best Practices
  * Naming Conventions
  * Building Reusable Tools
  * Output and Formatting
  * Error Handling
  * Performance
  * Language, Interop and .Net
  * Metadata, Versioning, and Packaging

One file each, with a TOC in each and a link to the top, a high-level TOC at the top and detailed ones in the two **Best Practices** and **Style Guide** files.

**Comment by mwjcomputing** [comment]
I am comfortable with this layout of the documents.

On Jun 1, 2015, at 7:50 PM, Joel Bennett <notifications@github.com<mailto:notifications@github.com>> wrote:


OK, after puzzling over it, here's my new proposed documents:

  *   Style Guide
     *   Code Layout and Formatting
     *   Function Structure
     *   Documentation and Commenting
     *   Readability
     *   Naming Conventions
  *   Best Practices
     *   Naming Conventions
     *   Building Reusable Tools
     *   Output and Formatting
     *   Error Handling
     *   Performance
     *   Language, Interop and .Net
     *   Metadata, Versioning, and Packaging

One file each, with a TOC in each and a link to the top, a high-level TOC at the top and detailed ones in the two Best Practices and Style Guide files.

-

**Comment by RamblingCookieMonster** [comment]
Not sure if it's covered somewhere, but it might help to include a table of contents. Much friendlier to browse through than individual files with odd names.

Cheers!

**Comment by Jaykul** [comment]
Added a TOC 
https://github.com/PoshCode/PowerShellPracticeAndStyle/blob/master/TableOfContents.md
