### ISSUE TITLE
ForEach vs ForEach-Object

### ISSUE THREAD

**Issue by pixelrebirth** [PoshCode/PowerShellPracticeAndStyle#65]
In your performance document you mention that:

```
$content = Get-Content file.txt

ForEach ($line in $content) {
  Do-Something -input $line
}
```

is _"However, this approach could offer extremely poor performance. If file.txt was a few hundred kilobytes, no problem; if it was several hundred megabytes, potential problem. Get-Content is forced to read the entire file into memory at once, storing it in memory (in the $content variable)."_

Now, this is inaccurate because the other way you mention ( | foreach-object) is actually exponentially slower due to serialization (this adds both cpu cycles and even MORE memory usage in total overall) of the data in the pipeline.

Here is some data, using your own example that proves my point. This is a get-content on a ~50MB file (java installer)

```
PS D:\Users\Kelcey.pixelrebirth\Downloads> measure-command {
>>> $content = get-content $pwd\jre-8u91-windows-x64.exe
>>>
>>> ForEach ($line in $content) {
>>>   $line.length
>>> }
>>> }


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 11
Milliseconds      : 466
Ticks             : 114668385
TotalDays         : 0.000132718038194444
TotalHours        : 0.00318523291666667
TotalMinutes      : 0.191113975
TotalSeconds      : 11.4668385
TotalMilliseconds : 11466.8385



PS D:\Users\Kelcey.pixelrebirth\Downloads> measure-command {
>>> $content = get-content $pwd\jre-8u91-windows-x64.exe |
>>> ForEach-Object -Process {
>>>   $_.length
>>> }
>>> }


Days              : 0
Hours             : 0
Minutes           : 1
Seconds           : 3
Milliseconds      : 36
Ticks             : 630365204
TotalDays         : 0.000729589356481481
TotalHours        : 0.0175101445555556
TotalMinutes      : 1.05060867333333
TotalSeconds      : 63.0365204
TotalMilliseconds : 63036.5204

```

Incidentally, the StreamReader was ~10 seconds slower than the foreach ($line in .. example....

```
PS D:\Users\Kelcey.pixelrebirth\Downloads> measure-command {
>>> $sr = New-Object -Type System.IO.StreamReader -Arg $pwd\jre-8u91-windows-x64.exe
>>>
>>> while ($sr.Peek() -ge 0) {
>>>    $line = $sr.ReadLine()
>>>    $line.length
>>> }
>>> }


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 21
Milliseconds      : 490
Ticks             : 214900262
TotalDays         : 0.000248727155092593
TotalHours        : 0.00596945172222222
TotalMinutes      : 0.358167103333333
TotalSeconds      : 21.4900262
TotalMilliseconds : 21490.0262
```

As per you wanting to start a discussion before re-writing a large portion of the guide I am starting the discussion. Id love to update the document to explain this phenomenon and share any sites I can re-find on the topic.

That being said a large enough file to fill up your memory would likely _HAVE_ to be done with the pipe technique else you will lag powershell/the system, ([gc]::collect() in the foreach loop helps, but still starts to hang the machine using upwards of 98% memory)... but the piped way is never going to be FASTER--- Maybe this memory issue is what you meant by performance--- to me that has a very different meaning.. this would need to be clarified in the write up as well.

I truly want to contribute to this, more from me will come in the next few weeks as I write the powershell style guide for my new shiny employment opportunity. (I will be using yours as a baseline and adding several things-- hoping some of them can make it into an accepted PR)

**Comment by rkeithhill** [comment]
> exponentially slower due to serialization

In this scenario, there is no serialization.  Get-Content `writes` a string to the output and that gets bound to the InputObject parameter.  That said, there is overhead to parameter binding process.

Also, I'm not sure this is a valid comparison.  Get-Content is rarely used to read exes.  And since it outputs line by line (no -Raw specified), it will read until it encounters a 0x0A character.  That could be a short line or a huge line - depending on the contents of the exe.  Why not try this experiment with a huge, text log file? I think that would be more representative. 

FWIW, some of this guidance may have been developed in earlier versions of PowerShell and may no longer be valid.  I've noticed for instance in v5 (maybe v4) that PowerShell logs data flowing down the pipeline and that logging "caches" data until the pipeline finishes which causes the very memory hoarding problem we sometimes try to avoid by streaming and operating on objects one at a time.

**Comment by dlwyatt** [comment]
To get the best performance balance out of Get-Content (without using up too much memory), use a combination of -ReadCount and a foreach loop down the pipeline:

```posh
Get-Content c:\some_massive_file.txt -ReadCount 1000 |
ForEach-Object {
    foreach ($line in $_) { $_.Length }
}
```

The ForEach-Object block will be processing up to 1000 lines at a time.  Since binding parameters and executing that block is the most expensive part of the process, you really notice a difference, and it's still reasonably safe for memory (unless your lines are so long that 1000 of them still fill up memory.)

**Comment by pixelrebirth** [comment]
The point has nothing to do with get-content... sure there are better ways to use that command. Anytime you use a pipeline that overheard you mentioned comes into play (causing in this example an 11 second process to take 61 seconds instead.) Get-content is just the easiest thing to demonstrate this on.

Let me take your suggestion of writing to a file...

```
PS D:\Users\Kelcey.pixelrebirth\Downloads> measure-command {
>>> $content = get-content $pwd\text.txt
>>>
>>> ForEach ($line in $content) {
>>>   $line.length
>>> }
>>> }


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 18
Milliseconds      : 698
Ticks             : 186981443
TotalDays         : 0.000216413707175926
TotalHours        : 0.00519392897222222
TotalMinutes      : 0.311635738333333
TotalSeconds      : 18.6981443
TotalMilliseconds : 18698.1443



PS D:\Users\Kelcey.pixelrebirth\Downloads>
PS D:\Users\Kelcey.pixelrebirth\Downloads>
PS D:\Users\Kelcey.pixelrebirth\Downloads> measure-command {
>>> $content = get-content $pwd\text.txt |
>>> ForEach-Object -Process {
>>>   $_.length
>>> }
>>> }


Days              : 0
Hours             : 0
Minutes           : 3
Seconds           : 39
Milliseconds      : 6
Ticks             : 2190060767
TotalDays         : 0.00253479255439815
TotalHours        : 0.0608350213055556
TotalMinutes      : 3.65010127833333
TotalSeconds      : 219.0060767
TotalMilliseconds : 219006.0767
```

This has absolutely nothing to do with get-content, I am talking about the performance of foreach-object vs foreach (http://bsonposh.com/archives/327 is one of many articles you can find online about this) to demonstrate I will use a simple numerical iteration...

```
PS D:\Users\Kelcey.pixelrebirth\Downloads> $range = 1..100000
PS D:\Users\Kelcey.pixelrebirth\Downloads> measure-command {$range | % {$_ * 9930}}


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 9
Milliseconds      : 576
Ticks             : 95762469
TotalDays         : 0.000110836190972222
TotalHours        : 0.00266006858333333
TotalMinutes      : 0.159604115
TotalSeconds      : 9.5762469
TotalMilliseconds : 9576.2469



PS D:\Users\Kelcey.pixelrebirth\Downloads> measure-command {foreach ($item in $range){$item * 9930}}


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 499
Ticks             : 4995527
TotalDays         : 5.7818599537037E-06
TotalHours        : 0.000138764638888889
TotalMinutes      : 0.00832587833333333
TotalSeconds      : 0.4995527
TotalMilliseconds : 499.5527
```

I may be wrong about it being because of serialization, that is how I understood the problem, each $_ input had to have a unique id associated to it for powershell to keep track--- that specific point I may need clarification on. Hopefully I can find the article that explained that aspect of it.

Hopefully you can see my point now however. If not I will keep digging for the specific one of the articles I read.

**Comment by pixelrebirth** [comment]
Here are some links:

http://consulting.risualblogs.com/blog/2014/06/27/powershell-foreach-vs-foreach-object/
http://www.itidea.nl/index.php/powershell-foreach-vs-foreach-object/
http://konab.com/foreach-vs-foreach-object-in-powershell/
http://powershell.com/cs/blogs/ebookv2/archive/2012/03/15/chapter-8-loops.aspx
http://tfl09.blogspot.com/2011/11/performance-with-powershell.html

While unrelated, this article makes an interesting point about the two:
http://techibee.com/powershell/difference-between-foreach-loop-and-foreach-object-in-powershell/2164

I have experienced drastic differences in script performance by simply ripping out foreach-object in favor of foreach time and time again with microsoft product script, vmware scripts, straight powershell scripts.... that is what motivates me to push on this issue. It is a very big deal, so long as you understand the memory gotcha it can drastically change script runtimes...

**Comment by dlwyatt** [comment]
Then I think you're missing the point.  If you use the foreach _statement_, you've automatically created code that won't work on large data sets.  If you're happy with that situation, then yes, it is the fastest way to process the collection.

Also, of the streaming options available, ForEach-Object is by far the slowest.  For example, try this and see how your numbers stack up:

```posh
filter Get-Length { $_.Length }
Measure-Command {
    $content = get-content $pwd\text.txt | Get-Length
}
```

**Comment by nightroman** [comment]
FWIW, `ForEach-Object` is easily replaced by

```powershell
... | .{process{ <# use $_ as usual #> }}
```

It is much faster than `ForEach-Object`, it produces less cryptic errors (if any), and it is streaming.

**Comment by pixelrebirth** [comment]
Filter was superior in speed to the foreach-object way:

```
PS D:\Users\Kelcey.pixelrebirth\Downloads> filter Get-Length { $_.Length }
PS D:\Users\Kelcey.pixelrebirth\Downloads> Measure-Command {
>>>     $content = get-content $pwd\text.txt | Get-Length
>>> }


Days              : 0
Hours             : 0
Minutes           : 1
Seconds           : 31
Milliseconds      : 398
Ticks             : 913989216
TotalDays         : 0.00105785788888889
TotalHours        : 0.0253885893333333
TotalMinutes      : 1.52331536
TotalSeconds      : 91.3989216
TotalMilliseconds : 91398.9216
```

The .{process way suggested has about the same results as the filter... baller technique-- but still only shows to prove my point that foreach is always faster.

```
PS D:\Users\Kelcey.pixelrebirth\Downloads> measure-command {
>>> get-content $pwd\text.txt | .{process{$_.length}}
>>> }
>>>


Days              : 0
Hours             : 0
Minutes           : 1
Seconds           : 33
Milliseconds      : 526
Ticks             : 935260504
TotalDays         : 0.00108247743518519
TotalHours        : 0.0259794584444444
TotalMinutes      : 1.55876750666667
TotalSeconds      : 93.5260504
TotalMilliseconds : 93526.0504
```

And for fun, here is another example from the document:

```
PS D:\Users\Kelcey.pixelrebirth\Downloads> measure-command {
>>> $sr = New-Object -Type System.IO.StreamReader -Arg $pwd\text.txt
>>>
>>> while ($sr.Peek() -ge 0) {
>>>    $line = $sr.ReadLine()
>>>    $line.length
>>> }
>>> }


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 10
Milliseconds      : 616
Ticks             : 106169965
TotalDays         : 0.000122881903935185
TotalHours        : 0.00294916569444444
TotalMinutes      : 0.176949941666667
TotalSeconds      : 10.6169965
TotalMilliseconds : 10616.9965
```

Maybe I am not being clear enough--

.net while loop - fastest overall with a very low ram hit, difficult to read
foreach - faster option, easy to read, if you can take a high ram hit
.{process/filter - faster than foreach-object -- more experience needed to read-- low ram hit
foreach-object - arguably easiest to read -- slowest option, low ram hit

Are all of you saying we should leave the performance page as is? I dont agree with that... there needs to be more information about how to optimize code- this is an important lesson IMO.

**Comment by pixelrebirth** [comment]
I guess my point is, foreach-object should be avoided.... you either use a superior piping method, foreach on smaller data sets or .net...

**Comment by rkeithhill** [comment]
How big of a dataset are you testing on?  Try a 1 GB log file in a x86 PowerShell console and see what the numbers are.  I'm not exactly sure what you'll find but I'm curious.  :-)  Remember the original issue was related to reading large amounts of data at once as required by the foreach statement.  You say *"if you can take a high ram hit"*.  I'm curious where the crossover point is in file size that makes the foreach statement slower - realizing it is dependent on how much RAM you have available.  That's why I suggest trying in a x86 PowerShell.  It is limited to ~1.5 GB of usermode memory.

**Comment by pixelrebirth** [comment]
Text.txt is a 1GB file. I have not tried the x86 console, but for obvious reasons this would be far more limiting. Keep in mind a 1GB worth of pipeline content is gargantuan and my 8GB machine handled it just fine. 

To me, there is no reason to ever use foreach-object --- period. Say for example you have a vm list.. of 10 vms in your datacenter.. sure foreach-object and foreach will nearly run the same... milliseconds vs seconds... but when that becomes 100 vms, 500 vms, 1000 vms etc ... foreach will start to shine, and still be well under the point of crushing your machine.

**Comment by pixelrebirth** [comment]
Thank you chris for the feedback. You are absolutely right. Each has a purpose. I believe we should spell that out more in the performance section.

**Comment by pixelrebirth** [comment]
I am converted. In thinking about the overall problem the risk of causing memory issues is not worth the benefit of time seen while doing specific lightning fast tasks.

You make a good point that in many cases the pipeline will be waiting, not the other way around. I believe we should still elaborate on this topic in the style guide.

After the discussion I would say I have been converted.

First try foreach-object, if there is a performance issue create a filter, else go to .net. I believe the fact that a pipeline is continuously in use is actually a good thing. The output stream is nice as well.

I resend my love of foreach and move to a love for .{process and filter .. both keep memory low and work relatively fast in comparison to foreach-object. To be fair, foreach-object is generally easier to write and cleaner for new people.

Thank you all for the feedback. I bow to your advice.

**Comment by KirkMunro** [comment]
Worth adding to all of this: ForEach-Object gets even better in PowerShell 5.1, with an approximate 50% performance increase.  See: https://msdn.microsoft.com/en-us/powershell/wmf/5.1/features-scenarios-cache/ps-engine-enhancements.  It will be interesting to re-run a few of these performance benchmarks in that release to see what the differences are then (maybe none, if these were done using the Fast Track for Windows 10, but PowerShell version wasn't mentioned here so I had to assume these comparisons were done using released non-preview versions of PowerShell).

**Comment by Jaykul** [comment]
The **completely artificial** delayed output example from @indented-automation is not only contrived, it's performance is the _opposite_ of any of the real-world examples of data collection which I can think of, unless perhaps you're using PowerShell to do heavy mathematics work? It is a strawman argument. You've simulated a *compute bound* data source. What *real world* data source takes that long for *each* output? Disk IO, Network IO, Database queries, etc. all have a long startup delay, and then nearly instantaneous output...

Contrived examples aside, the trade-off between memory and speed is a real trade off, but the example in the Best Practices guide wasn't about the trade-off between memory and speed.

That section is about the **trade-off between speed and style**. Or more to-the-point, the tradeoff between performance and _readability and maintainability_. In fact, I believe the real point of that section was to provide a counter argument against the assertion that pipelines make things harder to read.

**Comment by pixelrebirth** [comment]
I have discovered a flaw in foreach-object that is worth noting here...

foreach-object does not support continue -- it will break instead, the workaround is to do a return --- but that is horrible to need to return in the middle of your loop.....

Now I am more undecided again-- foreach supports continue, foreach-object does not.

**Comment by dlwyatt** [comment]
That's because ForEach-Object isn't a "loop", per se.  It's a cmdlet with begin, process and end blocks (same as any other advanced function or cmdlet.)
