### ISSUE TITLE
is there single page version of Practice And Style?

### ISSUE THREAD

**Issue by galkk** [PoshCode/PowerShellPracticeAndStyle#80]
Is there single version of this page in pdf/html format?
Current version is not very navigation/learning friendly.

I think that this is best example of what I'm asking form
https://google.github.io/styleguide/javaguide.html

**Comment by Jaykul** [comment]
There isn't, but there could be. Let me look into the github pages solution -- we decided originally that we didn't want to keep it all in one file in source control.

**Comment by kilasuit** [comment]
Its something that can be done by dynamically pulling the info from all the pages into a single page in a similar manner to what we have done for PSConf.eu 

Shouldn't be much work to do either tbh

**Comment by dzampino** [comment]
As a starting point, what do you think of this: https://github.com/dzampino/PowerShellPracticeAndStyle/blob/master/Merge-Markdown.ps1 

And the result: https://github.com/dzampino/PowerShellPracticeAndStyle/blob/master/combined.md

**Comment by Jaykul** [comment]
Not bad. We could probably even set up a build to run that.

**Comment by dzampino** [comment]
How do we want to move forward? I should probably clean that script up a bit before pulling. Do we want to change the directory structure at all? The single page file it creates seems to work nicely enough (could be optimized to read the individual files directly instead of copying and then reading), but all the links inside are, understandably, broken.

**Comment by Jaykul** [comment]
How about this, instead: https://www.gitbook.com/book/poshcode/powershell-practice-and-style/details

With [PDF](https://www.gitbook.com/download/pdf/book/poshcode/powershell-practice-and-style), [ePub](https://www.gitbook.com/download/epub/book/poshcode/powershell-practice-and-style) and [Mobi](https://www.gitbook.com/download/mobi/book/poshcode/powershell-practice-and-style) automatically generated on every commit. 

💥 🎤 💧 

😀
