### ISSUE TITLE
Book or FAQ?

### ISSUE THREAD

**Issue by Jaykul** [PoshCode/PowerShellPracticeAndStyle#94]
You may or may not have noticed that this guide is now available in [actual book format](https://poshcode.gitbooks.io/powershell-practice-and-style/content/) thanks to [gitbook](https://poshcode.gitbooks.io/) ...

In the process of setting that up, I had to consult the [gitbook docs](https://help.gitbook.com/) which are organized as a [faq](https://help.gitbook.com/basics/for-faq-documentation.html) ...

And that made me wonder if it would make sense to do this material that way as well -- what do y'all think? 

I think we could probably do both styles from one source, if we wanted too -- one of the motivations for using gitbook is to create an all-in-one single page pdf/ebook version as requested in #80, which the FAQ style doesn't seem to facilitate...

**Comment by darkoperator** [comment]
I love the idea

**Comment by Jaykul** [comment]
Looks like we'd have to organize it so each point was it's own article. I'm going to deem this not worth it, for now.
